name: Build, Test, and Release Server Monitoring Agent

on:
  push:
    tags:
      - 'v*' # This will trigger the workflow on pushing tags starting with 'v'

permissions:
  contents: write # This is required for creating releases and uploading assets

jobs:

  build:
    name: Build, Test, and Release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y sqlite3 libsqlite3-dev

    - name: Get dependencies
      run: make deps

    - name: Run tests
      run: make test

    - name: Build for all platforms
      run: make build-all

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          server-monitor-agent-linux-binaries.tar.gz
          build/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}